version: "3.8"

networks:
  cache_network:
    driver: bridge
    name: organizer_network

services:
  organizer_app:
    container_name: organizer_app
    build:
      context: "./"
      dockerfile: Dockerfile
#    image: organizer_app
    networks:
      cache_network:
        aliases:
          - organizer_network
    ports:
      - "9090:8080"
    expose:
      - "9090"