version: '3.8'

networks:
  cache_network:
    driver: bridge
    name: organizer_network

services:
  app:
    container_name: app
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      cache_network:
        aliases:
          - organizer_network
    ports:
      - "9090:8080"
    expose:
      - 9090
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/organizer
      SPRING_DATASOURCE_USERNAME: organizer
      SPRING_DATASOURCE_PASSWORD: organizer
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_JPA_HIBERNATE_SHOW_SQL: false
      JWT_SECRET: jwtsecret
  db:
    container_name: db
    image: postgres:13.3
    networks:
      cache_network:
        aliases:
          - organizer_network
    environment:
      POSTGRES_DB: organizer
      POSTGRES_USER: organizer
      POSTGRES_PASSWORD: organizer
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/